#!/bin/env bash
#
# A simple server side git update hook to prevent branch 
# names that have a '-' (dash) character in them.
#
# Useful if your repository is a puppet control repo.
#

current_branch="${1##*/}"

if [[ "${current_branch}" =~ '-' ]]; then
  echo "************************************************************"
  echo "*                                                           "
  echo "*  '${current_branch}' branch contains a '-' character.     "
  echo "*                                                           "
  echo "*  Branches in the puppet/control repository must not       "
  echo "*            contain a dash '-' character.                  "
  echo "*                                                           "
  echo "************************************************************"
  exit 1
else
  exit 0
fi  
